import React,{useState,useEffect} from 'react';
import {createRoot} from 'react-dom/client';
import {ArrowUpRight,ArrowRight,Play,Pause,ChevronLeft,ChevronRight,RotateCcw,Download,Code2,Layers3,Check,SlidersHorizontal,BookOpen,MoveRight,Printer,Sparkles} from 'lucide-react';
import {workshops,solve,fmt} from './engine';
import cpp from '../public/laboratorio.c?raw';
import './style.css';
import {CodeExecution,ExecutionTerminal} from './ExecutionPanels';
const methods=[{id:'gauss',name:'Gauss',label:'Eliminación gaussiana',subtitle:'Crear ceros. Resolver hacia atrás.',number:'01'},{id:'jordan',name:'Gauss-Jordan',label:'Gauss-Jordan',subtitle:'De la matriz a la identidad.',number:'02'},{id:'seidel',name:'Gauss-Seidel',label:'Gauss-Seidel',subtitle:'Aproximar. Actualizar. Repetir.',number:'03'}];

function App(){
 useEffect(()=>{document.body.classList.toggle("capture-mode",new URLSearchParams(location.search).has("captura"));},[]);
 const [method,setMethod]=useState('gauss'),[matrix,setMatrix]=useState(workshops.map(r=>r.map(String))),[eq,setEq]=useState(3),[unknown,setUnknown]=useState(3),[tol,setTol]=useState(5),[result,setResult]=useState(()=>solve(workshops)),[step,setStep]=useState(0),[playing,setPlaying]=useState(false),[speed,setSpeed]=useState(1600),[error,setError]=useState(''),[isWorkshop,setIsWorkshop]=useState(true),[dirty,setDirty]=useState(false);
 const current=result.steps[step]||result.steps[0],active=methods.find(m=>m.id===method),end=step===result.steps.length-1;
 useEffect(()=>{if(!playing)return;const id=setInterval(()=>setStep(s=>{if(s>=result.steps.length-2){setPlaying(false);return result.steps.length-1;}return s+1;}),speed);return()=>clearInterval(id)},[playing,speed,result]);
 function run(m=method,mat=matrix){try{if(eq!==unknown)throw Error('La cantidad de ecuaciones debe coincidir con la de incógnitas.');if(eq!==mat.length)throw Error('Pulsa «Crear matriz» para aplicar las dimensiones nuevas.');if(mat.some(r=>r.some(v=>String(v).trim()==='')))throw Error('Completa todos los coeficientes y términos independientes.');setResult(solve(mat.map(r=>r.map(Number)),m,Number(tol)));setMethod(m);setStep(0);setPlaying(false);setDirty(false);setError('');}catch(e){setError(e.message);setPlaying(false)}}
 function resize(){if(eq!==unknown||!Number.isInteger(eq)||eq<1||eq>10){setError('Introduce cantidades iguales entre 1 y 10. La web admite hasta 10; el C usa tamaño dinámico.');return;}setMatrix(Array.from({length:eq},(_,i)=>Array.from({length:eq+1},(_,j)=>String(i===j?1:0))));setDirty(true);setIsWorkshop(false);setPlaying(false);setError('');}
 function reset(){setTol(5);setEq(3);setUnknown(3);setMatrix(workshops.map(r=>r.map(String)));setIsWorkshop(true);setResult(solve(workshops,method,5));setStep(0);setPlaying(false);setDirty(false);setError('');}

 return <><header className="header"><a className="brand" href="#"><span className="brand-icon"><Layers3 size={21}/></span> Laboratorio de métodos numéricos</a><nav><a href="#problema">El problema</a><a href="#laboratorio">Laboratorio</a><a href="#conclusiones">Conclusiones</a></nav><a className="header-cta" href="/laboratorio.c" download>Código C <ArrowUpRight size={15}/></a></header>
 <main><section className="hero"><div className="hero-copy"><div className="eyebrow"><span/> LABORATORIO 02 <span className="eyebrow-separator">/</span> MÉTODOS NUMÉRICOS</div><h1>Laboratorio de<br/><span>métodos numéricos</span></h1><a href="#laboratorio" className="primary">Explorar el laboratorio <ArrowRight size={17}/></a><div className="hero-foot"><span>01 — Gauss</span><span>02 — Gauss-Jordan</span><span>03 — Gauss-Seidel</span></div></div><div className="hero-art" aria-label="Representación de una matriz de tres por tres"><div className="orbit orbit-one"/><div className="orbit orbit-two"/><div className="floating-chip chip-top"><span className="tiny-dot"/> SISTEMA DE ECUACIONES</div><div className="glass-matrix"><div className="matrix-label">A · x = b <Sparkles size={15}/></div><div className="art-equation"><span className="bracket">[</span><div className="art-grid">{['0.52','0.20','0.25','0.30','0.50','0.20','0.18','0.30','0.55'].map((s,i)=><span key={i} className={i%4===0?'diagonal':''}>{s}</span>)}</div><span className="bracket">]</span></div><div className="matrix-footer"><span>3 ecuaciones</span><span>3 incógnitas</span></div></div><div className="floating-chip chip-bottom"><span className="check-circle"><Check size={14}/></span> Matriz, código y terminal.</div><div className="art-caption">GAUSS · GAUSS-JORDAN · GAUSS-SEIDEL</div></div></section>
 <section id="problema" className="problem"><div className="section-kicker">EJEMPLO PRINCIPAL · ERROR DEL 5 %</div><div className="problem-heading"><h2>Problema del laboratorio</h2><span className="pill">Caso de ingeniería mecánica</span></div><div className="problem-grid"><div><p>Un ingeniero mecánico requiere <strong>4.800 kg de acero</strong>, <strong>5.810 kg de plástico</strong> y <strong>5.690 kg de aluminio</strong>. Los materiales se necesitan para la construcción de vehículos. La empresa dispone de tres talleres, cada uno con la composición indicada.</p><p className="question">¿Cuántos kg debe tomar de cada taller?</p><div className="variable-note">x₁, x₂, x₃ = masa total obtenida de cada taller, en kg.</div></div><div className="composition"><table><thead><tr><th>COMPOSICIÓN</th><th>Taller 1</th><th>Taller 2</th><th>Taller 3</th></tr></thead><tbody>{[['Acero','52 %','20 %','25 %'],['Plástico','30 %','50 %','20 %'],['Aluminio','18 %','30 %','55 %']].map((r,i)=><tr key={i}>{r.map((c,j)=><td key={j}>{j===0&&<span className={'material-dot material-'+i}/>} {c}</td>)}</tr>)}</tbody></table></div></div></section>
 <section id="laboratorio" className="lab"><div className="section-kicker">EJECUCIÓN PASO A PASO</div><div className="section-heading"><div><h2>El laboratorio<span className="pink-dot">.</span></h2><p>Observa la matriz, la línea activa y sus variables.</p></div><span className="live-badge"><span/> INTERACTIVO</span></div><div className="method-tabs">{methods.map(m=><button key={m.id} className={method===m.id?'method active':'method'} onClick={()=>run(m.id)}><span className="method-number">{m.number}</span><span><strong>{m.name}</strong><small>{m.subtitle}</small></span><ArrowUpRight size={20}/></button>)}</div>
 <details className="editor"><summary><SlidersHorizontal size={17}/><strong>Configura tu sistema</strong><span>{matrix.length} × {matrix.length} · {isWorkshop?'Problema de las talleres':'Sistema personalizado'}</span><span className="edit-link">Editar matriz +</span></summary><div className="editor-body"><div className="inputs"><label>Ecuaciones<input aria-label="Cantidad de ecuaciones" type="number" min="1" max="10" value={eq} onChange={e=>{setEq(Number(e.target.value));setDirty(true)}}/></label><label>Incógnitas<input aria-label="Cantidad de incógnitas" type="number" min="1" max="10" value={unknown} onChange={e=>{setUnknown(Number(e.target.value));setDirty(true)}}/></label><button className="secondary" onClick={resize}>Crear matriz</button><label>Tolerancia de Seidel (%)<input type="number" min="0.001" max="100" step="any" value={tol} onChange={e=>{setTol(e.target.value);setDirty(true)}}/></label></div><p>Introduce los coeficientes de cada fila y su término independiente b. La interfaz admite de 1 a 10 incógnitas; el programa C utiliza dimensiones dinámicas.</p><div className="input-matrix">{matrix.map((row,i)=><div key={i}><span>F{i+1}</span>{row.map((v,j)=><input key={j} type="number" step="any" aria-label={j===row.length-1?`Término independiente fila ${i+1}`:`Fila ${i+1} coeficiente ${j+1}`} value={v} onChange={e=>{setMatrix(a=>a.map((r,ri)=>ri===i?r.map((c,cj)=>cj===j?e.target.value:c):r));setDirty(true);setIsWorkshop(false);setPlaying(false)}}/>)}</div>)}</div><div className="editor-actions"><button className="primary" onClick={()=>run()}>Resolver sistema <ArrowRight size={16}/></button><button className="secondary" onClick={reset}>Cargar ejemplo principal</button></div></div></details>{error&&<div role="alert" className="notice error">{error}</div>}{dirty&&<div className="notice">Hay cambios pendientes. Pulsa «Resolver sistema» para actualizar el desarrollo.</div>}
 <div className="workspace"><div className="math-panel"><div className="panel-top"><span><Layers3 size={16}/> DESARROLLO VISUAL</span><span className="mini-pill">{active.label}</span></div><div className="stage"><div className="stage-title"><span className="step-label">PASO {String(step+1).padStart(2,'0')}</span><span className="muted">Matriz aumentada [ A | b ]</span></div><div className="matrix-scroll"><div className="working-matrix" style={{'--cols':current.matrix.length+1}} key={`${method}-${step}`}><div className="column-labels">{current.matrix[0].map((_,j)=><span key={j}>{j===current.matrix.length?'b':`x${j+1}`}</span>)}</div>{current.matrix.map((r,i)=><div key={i} className={'matrix-row '+(current.rows.includes(i)?'highlight':'')}>{r.map((v,j)=><span key={j} className={`${j===r.length-1?'rhs':''} ${current.cell?.[0]===i&&current.cell?.[1]===j?'active-cell':''}`}>{fmt(v)}</span>)}</div>)}</div></div><div className="matrix-legend"><span className="legend-dot"/> Fila activa <span className="legend-line"/> Término independiente</div></div><div className="explanation" aria-live="polite"><span className="explain-icon"><MoveRight size={21}/></span><div><h3>{current.title}</h3><p>{current.description}</p></div></div>{(method==='seidel'||current.tag==='back'||current.tag==='result')&&<div className="values">{current.x.map((v,i)=><span key={i}>x{i+1} <strong>{fmt(v)}</strong></span>)}</div>}<div className="player"><div className="progress"><div style={{width:`${(step+1)/result.steps.length*100}%`}}/></div><div className="player-controls"><button aria-label="Reiniciar pasos" onClick={()=>{setStep(0);setPlaying(false)}}><RotateCcw size={17}/></button><button aria-label="Paso anterior" disabled={step===0} onClick={()=>{setStep(s=>s-1);setPlaying(false)}}><ChevronLeft size={20}/></button><button className="play" aria-label={playing?'Pausar':'Reproducir'} onClick={()=>{if(end)setStep(0);setPlaying(!playing)}}>{playing?<Pause size={17}/>:<Play size={17}/>}</button><button aria-label="Paso siguiente" disabled={end} onClick={()=>{setStep(s=>s+1);setPlaying(false)}}><ChevronRight size={20}/></button><span>{step+1} <span className="muted">/ {result.steps.length}</span></span><select aria-label="Velocidad de reproducción" value={speed} onChange={e=>setSpeed(Number(e.target.value))}><option value={2400}>0.5×</option><option value={1600}>1×</option><option value={800}>2×</option></select></div><input aria-label="Ir al paso" className="step-slider" type="range" min="0" max={result.steps.length-1} value={step} onChange={e=>{setStep(Number(e.target.value));setPlaying(false)}}/></div></div>
 <CodeExecution current={current} previous={result.steps[step-1]} step={step} playing={playing}/></div>
 <ExecutionTerminal steps={result.steps} step={step} playing={playing} method={active.name} onNext={()=>{setStep(s=>Math.min(s+1,result.steps.length-1));setPlaying(false)}} onPrevious={()=>{setStep(s=>Math.max(s-1,0));setPlaying(false)}} onPlay={()=>{if(end)setStep(0);setPlaying(!playing)}} onReset={()=>{setStep(0);setPlaying(false)}}/>

 <div className="status-bar"><span className="status-symbol">{result.status==='solved'||result.status==='converged'?<Check size={18}/>:<SlidersHorizontal size={18}/>}</span><div><strong>{result.status==='solved'?'Solución única calculada':result.status==='converged'?`Tolerancia alcanzada en ${result.iterations} iteraciones`:result.message}</strong><span>{result.residual!==undefined?`Residuo máximo |Ax − b|: ${result.residual.toExponential(3)}`:'Revisa el sistema antes de continuar.'}{method==='seidel'?' · Inicio x = 0 · Máximo 100 iteraciones':' · Pivoteo parcial'}</span></div><button className="text-button" onClick={()=>{setStep(result.steps.length-1);setPlaying(false)}}>Ver resultado <ArrowRight size={16}/></button></div>{method==='seidel'&&result.dominant===false&&<div className="notice">La matriz no es estrictamente dominante por filas. Eso no implica divergencia, pero este criterio no garantiza la convergencia.</div>}<p className="implementation-note">Puedes pausar, avanzar o retroceder: la terminal, la matriz y las variables recuperan el mismo paso. Descarga el C para ejecutarlo en un compilador.</p></section>
 <Conclusions/><section className="download-card"><div className="download-icon"><Code2 size={29}/></div><div><div className="section-kicker">LISTO PARA EXPLICAR</div><h2>Programa C documentado</h2><p>Un archivo C documentado. Tres métodos. Cualquier sistema cuadrado.</p></div><a className="primary" href="/laboratorio.c" download><Download size={17}/> Descargar C</a></section><section className="report"><a className="secondary" href="/capturas/index.html" target="_blank" rel="noreferrer">Capturas y explicaciones de los tres métodos</a><div><h3>Tu guía para la sustentación</h3><p>Define las incógnitas → construye la matriz → explica las operaciones → verifica el residuo → interpreta los volúmenes.</p></div><button className="secondary" onClick={()=>window.print()}><Printer size={17}/> Imprimir informe</button></section><section className="print-only"><h1>Laboratorio 2 · Métodos de ecuaciones simultáneas</h1><p>Estudiante: ____________________ Docente: ____________________</p><p>Institución: ____________________ Fecha: ____________________</p><h2>Introducción</h2><p>Se estudian tres algoritmos para resolver sistemas lineales cuadrados y su aplicación a una mezcla de materiales para fabricar vehículos. Se comparan operaciones directas e iteraciones, verificando los resultados mediante el residuo.</p><h2>Ejecución seleccionada · {active.label}</h2>{result.steps.map((s,i)=><div className="printed-step" key={i}><h3>{i+1}. {s.title}</h3><p>{s.description}</p><pre>{s.matrix.map(r=>r.map(fmt).join('     ')).join('\n')}</pre></div>)}<h2>Código fuente documentado</h2><pre>{cpp}</pre></section></main><footer><a className="brand" href="#">Laboratorio de métodos numéricos</a><span>LABORATORIO 02 · ECUACIONES SIMULTÁNEAS</span><span>Gauss · Gauss-Jordan · Gauss-Seidel</span></footer></>;
}
function Conclusions(){const g=solve(workshops),s=solve(workshops,'seidel');return <section className="conclusions" id="conclusiones"><div className="section-kicker">RESULTADOS</div><h2>Resultados del problema</h2><p>Resultados del problema original de las talleres, usando los métodos directos.</p><div className="result-cards">{g.x.map((x,i)=><div key={i}><span>TALLER 0{i+1}</span><strong>{fmt(x)} <small>kg</small></strong><p>{['Mezcla con 52 % de acero','Mezcla con 50 % de plástico','Mezcla con 55 % de aluminio'][i]}</p></div>)}</div><div className="verification"><Check size={18}/><span>Verificación con valores sin redondear: <strong>4.800 kg</strong> de acero + <strong>5.810 kg</strong> de plástico + <strong>5.690 kg</strong> de aluminio. Total: <strong>16.300 kg</strong>.</span></div><div className="answers"><article><span>01 / VELOCIDAD</span><h3>¿Cuál converge más rápido?</h3><p>Gauss y Gauss-Jordan son métodos directos: no convergen por iteraciones. Para un sistema pequeño, Gauss suele requerir menos operaciones que Jordan. Seidel alcanza el criterio del 5 % en <strong>{s.iterations} iteraciones</strong> en este caso; no es una comparación de tiempos medidos.</p></article><article><span>02 / PRECISIÓN</span><h3>¿Cuál es más preciso?</h3><p>Con esta tolerancia, los métodos directos dejan un residuo mucho menor. Seidel termina con un residuo máximo de <strong>{fmt(s.residual)} kg</strong>. Reducir la tolerancia puede mejorar su aproximación, a costa de más iteraciones.</p></article><article><span>03 / EXACTITUD</span><h3>¿Cuál es más exacto?</h3><p>En aritmética exacta, los métodos directos obtienen la solución exacta. En C y en la web usamos punto flotante: hay redondeo. Para este caso, Gauss y Jordan están más cerca de la solución de referencia; no hay un ganador universal.</p></article></div><details className="theory"><summary>Entender el 5 % y la solución de referencia <ChevronRight size={17}/></summary><p>El criterio es maxᵢ |(xᵢ actual − xᵢ anterior) / xᵢ actual| × 100 ≤ 5 %. No garantiza un error verdadero menor al 5 %. Si el valor actual es cero y cambia respecto al anterior, el error relativo se toma como infinito; si ambos son cero, se toma como cero.</p><p>Solución racional de referencia: x₁ = 172500/43, x₂ = 308000/43 y x₃ = 220400/43 kg. Gauss-Seidel obtiene ({s.x.map(fmt).join('; ')}) kg. La segunda fila tiene igualdad entre el valor diagonal y la suma de los otros coeficientes: no hay dominancia estricta en todas las filas. En esta ejecución sí se alcanza la tolerancia; no se presupone convergencia para otros sistemas.</p></details></section>}
createRoot(document.getElementById('root')).render(<App/>);



